### ISSUE TITLE
Issues testing an API imported from another file

### ISSUE THREAD

**Issue by ianthetechie** [timothycrosley/hug#180]
The testing facilities included in hug are really nice. However, when writing tests against your own APIs declared in separate files, there appear to be two small issues.

First, the README seems to indicate that you can test by passing in the module with your API to `hug.test.get` or a similar function. However, it appears that you actually need to pass `your_module.__hug__` as the first argument to `hug.test.get`. I'm not sure if this is just outdated documentation or a legitimate bug.

Second, assuming the above is the correct way to test a module, py.test seems to hang after finishing the tests. This appears to only be an issue when importing APIs from another module. Declaring API endpoints inline seems to work, but this is obviously not feasible when writing tests against your nicely structure set of API files ;) I'm guessing that there is some "server" thread that is not exiting after the tests?

**Comment by ianthetechie** [comment]
Update: Potentially false alarm. I may actually be kicking off a long-running process somewhere in my database code. Stand by...

**Comment by ianthetechie** [comment]
Yup; the py.test hang was my bad. My logging happens out-of-process via multiprocessing, and I was not tearing this down. Sorry for the false alarm. However, I still am curious about the need to pass `your_module.__hug__` rather than just `your_module` to `hug.test.get`.

**Comment by timothycrosley** [comment]
Hi @ianthetechie,The first issue was an unintended regression in the development branch. I've fixed it so that now you can pass in either an API instance or a module and it will work.
The initial reason for the change was as pointed towards to simplify testing code, as 
`hug.test.get(sys.modules[__name__], ...)` is less clear then `hug.test.get(hug.API(__name__), ...)`, now both are supported.
