### ISSUE TITLE
extend_api not working?

### ISSUE THREAD

**Issue by ariscn** [timothycrosley/hug#313]
`api.py`:

    from hug import get, extend_api

    from .handlers import a, b

    @get('/bar')
    def bar():
        return 'bar'

    @extend_api('/api')
    def api():
        return [a, b, bar]

`handlers.py`:

    from hug import get

    @get('a')
    def a():
        return 'a'

    @get()
    def b():
        return 'b'

When I hit `/`:

    # Outer part of response omitted
    "handlers": {
        "/bar": {
            "GET": {
                "examples": [
                    "http://localhost:8000/bar"
                ],
                "outputs": {
                    "content_type": "application/json",
                    "format": "JSON (Javascript Serialized Object Notation)"
                }
            }
        }
    }

My `a` and `b` endpoints are nowhere to be found?

**Comment by timothycrosley** [comment]
Hi @ariscn,

Thanks for submitting this question. The reason this is not working as you expect is because `hug.extend_api` is for extending an API to include entire modules not individual functions (though this may be a cool feature to add in the future). To get the behavior you are anticipate simply change api.py to: 

    from hug import get, extend_api

    import handlers


    @get('/api/bar')
    def bar():
        return 'bar'


    @extend_api('/api')
    def api():
        return [handlers]

The key thing here, again, being that you are extending your API to include entire addition *modules* and not piecemeal functions etc.

Thanks! And please let me know if this works for you.

~Timothy

**Comment by ariscn** [comment]
@timothycrosley Yep, that works. But I have another issue, which is that I've attached an output formatter to the root API, which does not seem to apply any endpoints under `extend_api`.

I can see in the 404 docs that the extended endpoints are using the default JSON formatter. I override the formatter in the imported module, but this seems a bit hacky? My goal is to configure all of my API "stuff" - middleware, formatters, authentication, etc - in one place, and all of my endpoints in a separate module.

Also, when I change the output formatter, the 404 docs show it as `format: null`. I expected to see the function name, or for `default_output_format` to take a `pretty_name` argument.

**Comment by timothycrosley** [comment]
This is now fixed here: https://github.com/timothycrosley/hug/pull/373/files,

Thanks!

~Timothy
