### ISSUE TITLE
Order matters for router modifications?

### ISSUE THREAD

**Issue by ariscn** [timothycrosley/hug#317]
from hug import default_output_format
    from hug.output_format import json as json_format
    from hug.route import API

    def index():
        return {'healthy': True}

    # Fails
    router = API(__name__)

    router.urls('/').get()(index)

    @default_output_format()
    def test(data):
        data['success'] = 'errors' not in data
        return json_format(data)

    # Works
    router = API(__name__)

    @default_output_format()
    def test(data):
        data['success'] = 'errors' not in data
        return json_format(data)

    router.urls('/').get()(index)

Changing the output format *before* adding routes works, but fails if done after. This is, well, rather unexpected.

**Comment by timothycrosley** [comment]
Hi @ariscn,

Yes this is correct, and known. I hope to change this before the next release - but it's easy to explain why this is the case:

You can think of each hug decorator as compiling the requested interfaces from given code as soon as it is told to. It "compiles" them into the most efficient implementation caching any state or other information that would be used to handle an individual request. This is why it's so fast at handling requests.

However, it has the disadvantage of that if you define API state changing things (like default output formats) *after* you define endpoints they do not effect the existing endpoints, since they've already been "compiled". In order to resolve this while maintaining the request speed, I plan on moving all endpoint compilation to be done either on the first request of that endpoint - or when I can verify everything is set (say when a user starts a web-server). This will add a negligible amount to startup time, but keep quick response times and enable things like default output formats to be changed independant of route locations.

Thanks!

~Timothy

**Comment by ariscn** [comment]
Thanks for the thorough reply! Glad to hear you're planning on improving the way this works in the near term. Until then, this is the sort of thing I'd expect to see in the docs, in either a "Known Issues" or "Gotchas" section.

**Comment by timothycrosley** [comment]
@ariscn,

Agreed! I don't have a gotchas section yet, or an FAQ, I'll add one before the next release to handle things like this. Though, hopefully with this fixed there will not be many :)

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has been fixed in Develop and is ready for the next release

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
