### ISSUE TITLE
CLI: keyword arguments support

### ISSUE THREAD

**Issue by mhavel** [timothycrosley/hug#321]
I can't  find a way to use keyword arguments with the CLI decorator.

Eg.:

```python
@hug.cli()
def func(**kwds):
    return kwds
```

won't work :( Of course, I'm not even sure how you'd pass the keyword arguments on the CLI:

```bash
hug -f api.py -c func a=1 -b cool --a_long_name=3.4
```

Maybe related to the bug with default values for CLI too? Or just not implemented yet?

**Comment by timothycrosley** [comment]
Hi @mhavel,

`**kwargs` were intentionally not supported for CLI commands since they are a pretty vague concept for command lines as you mentioned (it get's even harder to parse when you start talking about mixing with concepts settings that take variable number of arguments). However, cli does take *args if you set them, which are basically anything that argparse isn't able to parse which is passed in - split by space. This could work for your use case (with some additional parsing). I may think some more about how to implement **kwargs support even with the parsing difficulty.

Thanks!

~Timothy

**Comment by mhavel** [comment]
Thanks @timothycrosley, that makes sense. I did just test the "leftovers" arguments passing, and it does work well. Just needs a bit of work behind as you said.

**Comment by timothycrosley** [comment]
Implemented here: https://github.com/timothycrosley/hug/pull/389/files and ready for the next release

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
