### ISSUE TITLE
request.params not populated with POST data

### ISSUE THREAD

**Issue by dreadwestern** [timothycrosley/hug#324]
Not sure if this is a bug or a feature, but when testing, I notice that POST data isn't being populated in request.params. However, I do see the POST data being populated in body.

Test setup:
```
# test_post_vars.py
import hug

@hug.post('/echo')
def on_post(request, response, body):
    return {
        'method': request.method,
        'params': request.params,  # request.params outputs 'null' 
        'post_body': body # body outputs a dict of key/value pairs passed in
    }
```
My initial expectation is that the request.params dict would contain all GET and POST key/value pairs being sent, for easier use in the handler. However, I can see the advantage of keeping these as separately defined sets. Just wanted to clarify the expected behavior for the framework. Thanks!

**Comment by timothycrosley** [comment]
Hi @dreadwestern,

Great question! It is indeed a "feature". `body` contains hug's understanding of all parameters based on plugins installed (like `hug_yaml`) etc. But never changes the source objects it uses. In this way, you can always trace back to where a value came from if you need this information for an endpoint. It also encourages separating your logic from the underlying request object when possible and thinking instead of API interfaces and the arguments in which they take - though sometimes the information provided from the request is necessary.

Thanks!

~Timothy Crosley
