### ISSUE TITLE
Custom decorators

### ISSUE THREAD

**Issue by gemedet** [timothycrosley/hug#345]
In external.py:
```
def external_decorator(function):
    def decoration(request, response):
        return function()
    return decoration
```
In main.py:
```
from external import external_decorator

def internal_decorator(function):
    def decoration(request, response):
        return function()
    return decoration

@hug.get('/foo')
@internal_decorator
def foo():
    return 'foo'

@hug.get('/bar')
@external_decorator
def bar():
    return 'bar'
```
Accessing `localhost:8000/foo` works as expected, but `localhost:8000/bar` results in "The API call you tried to make was not defined". Am I using these right?

**Comment by jmmills** [comment]
Does it work if you use functools.wraps?

**Comment by gemedet** [comment]
You mean like this?
```
def external_decorator(function):
    @hug.wraps(function)
    def decoration(request, response):
        return function(request, response)
    return decoration
```
That works, but then I have to define the endpoints with the request & response arguments, which is unnecessary if only the decorator uses them:
```
@hug.get('/bar')
@external_decorator
def bar(request, response):
    return 'bar'
```

**Comment by jmmills** [comment]
@gemedet I'm guessing it has to do with preserving the function object annotations. You have to remember that decorators stack/chain, so the external_decorator is getting handed to the ```@hut.get``` decorator as a function object... it's likely that because the external_decorator isn't using ```functools.wraps``` it isn't preserving the properties of the original function. Hug (iirc) uses this type of function introspection to determine what to do with a router handler.

It's a pretty common [pattern](http://thecodeship.com/patterns/guide-to-python-function-decorators/)

**Comment by gemedet** [comment]
All right, thanks!
