### ISSUE TITLE
How to get the post request body

### ISSUE THREAD

**Issue by faith0811** [timothycrosley/hug#352]
Hi,

The falcon ``request`` has a method ``stream.read()`` which can read the request body, but it can only be read once. Does hug have a way to get the original post request body?(I need that for authorization)

For now, my solution is add a request middleware like below:

```python
@hug.request_middleware()
def perm_req_body(request, response):
    body = request.stream.read()
    request.stream.read = lambda: body
```

But I'm not sure if this is safe enough.

Thanks!

**Comment by vortec** [comment]
The [documentation](http://falcon.readthedocs.io/en/stable/api/request_and_response.html#Request.stream) says it's a file-like object, so you should be able to seek to the beginning via ``request.stream.seek(0)`` before reading.

**Comment by faith0811** [comment]
hi @vortec ,

Thanks for reply.

But the ``request.stream.seek()`` seems actually not existed.

```
AttributeError: 'Body' object has no attribute 'seek'
```

**Comment by timothycrosley** [comment]
This is a Falcon limitation that is inherited by hug, your solution is solid. The reason for this is that it requests a stream that no longer exists after being read - unless you store it somewhere. In order to support seek universally Falcon would need to always have a copy of the data saved to the object - which would add generally uneeded overhead.

**Comment by rubgombar1** [comment]
Hi all!

I am working with hug and i need get the body params from the request. 

In development, i use this snippet and works well, i can call to get the body params in any place but when i deploy the application in a Apache with mod_wsgi, when i try rewrite the read() functions, i get an error with the following description: **AttributeError: 'mod_wsgi.Input' object attribute 'read' is read-only**

I can't implements my functionality due to this limitation, please, can anybody help me?

Thanks!

**Comment by rubgombar1** [comment]
Hi all! 

Yesterday I could not find but today i found a solution for the problem with Apache mod_wsgi:

```
@hug.request_middleware()
def process_data(request, response):
    body = request.stream.read()
    stream = io.BytesIO(body)
    request.body_params = body.decode('utf-8')
    request.stream = stream
```

The stream object with mod_wsgi is read only, then we can not override the read function of the stream, so I read the stream and I create a BytesIO object as the new stream and replace it by the old stream.

Regards!
