### ISSUE TITLE
Performance Issues gunicorn/heroku

### ISSUE THREAD

**Issue by pmart123** [timothycrosley/hug#381]
I ported a flask app that consists of get requests/JSON, and interacts with psycopg2/sqlalchemy primarily to hug. Using a heroku starter instance, my response times are roughly 2-3 times worse than the equivalent flask app, which I am not expecting. This is for single response performance (10 ms vs. 30) to also large variance on worst(500 ms).
### My routes generally look like:

``` python

engine = create_engine()

def cors_support(response, *args, **kwargs):
    response.set_header('Access-Control-Allow-Origin', '*')

@hug.get('/entity/search', requires=cors_support)
def entity_search(term: str):
    return search_entities(engine, term)
```
### My procfile for gunicorn looks like:

``` bash
web: gunicorn api_package.run:__hug_wsgi__
```

But I have also tried:

``` bash
web: gunicorn -b 0.0.0.0:$PORT api_package.run:__hug_wsgi__
```

versus the flask:

``` bash
web: gunicorn --pythonpath api_package run:app --log-file=-
```

Given the expected performance versus actual, is there any potential reason or issue that could be used to address and investigate the matter?

**Comment by timothycrosley** [comment]
It's hard for me to see from the sample code alone - your configuration certainly doesn't look suspect. However, in the past when I've ran into performance issues it's usually because of connection / disconnection to the database - I would recommend profiling the application and seeing where the slowdown is occurring. If you can pinpoint it to request handling (hug) than that would be our highest priority for this project as performance is very important for us - certainly we would add the specific slowdown use case to our benchmarks. Another recommendation would be to ensure that you have Cython installed before hug, if you are able to on the environment in question. If you would like to discuss this in more detail please feel free to directly message me on gitter (https://gitter.im/timothycrosley/hug) and we can try to pinpoint it together.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
Going ahead and closing this issue, as I didn't see any more information given and have been unable to repodruce
