### ISSUE TITLE
SSL Terminated Environment

### ISSUE THREAD

**Issue by philipbjorge** [timothycrosley/hug#384]
Hi,
We're running hug in behind a load balancer that terminates SSL.
That is causing our documentation to generate examples that are `http://host_name/...`

Could you point me in the right direction to how I would configure a protocol or entire base url manually?

**Comment by philipbjorge** [comment]
One way to do this is the following...

```
@hug.not_found()
def handle_404(request, hug_api):
    http = hug_api.http
    return http.documentation("https://custom-base-url.com", http.determine_version(request, False))
```

**Comment by philipbjorge** [comment]
This now needs to be changed to...
`return http.documentation(api_version=http.determine_version(request, False), prefix=config.API_BASE_URL)`

After this change -- https://github.com/timothycrosley/hug/commit/af23bd553c0fbdebbaa5d8241aae34130782b63b

**Comment by briceparent** [comment]
Hi!
I'm having the same question, I think. I'm not running a load balancer, but I have nginx with SSL encryption, so my users need to access my API using https, but my documentation shows examples with http (which is prohibited, only https is authorized).

The problem is not to redirect incoming http connections to https, but just to have the documentation display examples with https. (or even better, to use the same protocol as I'm using to display the documentation page, so that the links are still correct on my development station, with http).

If I misunderstood the original question and should post this in a new issue, please tell me!

Brice

**Comment by briceparent** [comment]
In fact, it gives me links like this:
http://mydomain.com:443/hello
which to my knowledge doesn't make much sense... and when following it, Nginx returns a 400 error saying "The plain HTTP request was sent to HTTPS port".

**Comment by tuffnatty** [comment]
Pull request: #708
