### ISSUE TITLE
class based routing doesn't inherit templated parameters

### ISSUE THREAD

**Issue by davidhyman** [timothycrosley/hug#464]
On an API that looks something like this - 
```python
@hug.object.urls('/objects/{model}/', requires=auth_verified)
class CRUD:

    @hug.object.patch('/{guid}')
    def set_by_guid(self, model, guid, **kwargs):
        # Update an existing object

    @hug.object.get()
    def get_all_of_type(self, model: hug.types.text,...)
        # Get existing objects
```

1. `Examples` doc generation are definitely broken using this approach - they don't build from inherited path but instead, each sub-route is based directly off root, without versioning, or the class's base route.

2.  The routing itself is 'broken', in that this kind of templating does not provide the parameters as expected.

A solution is to route like this - 
```python
@hug.object.urls('/objects/{model}', requires=auth_verified)
@hug.object.urls('/objects/{model}/{guid}', requires=auth_verified)
class CRUD:

    @hug.object.patch()
    def set_by_guid(self, model, guid, **kwargs):
        # Update an existing object

    @hug.object.get()
    def get_all_of_type(self, model: hug.types.text,...)
        # Get existing objects
```
I find this a bit strange, because it means exposing the same parameters to every child method. Additonally, overloading the class with urls means you can't overload contained methods e.g. you can't define both of these methods:
```python
@hug.object.get(examples=['/fruit/apple'])
    def get_by_guid(self, model, guid):
        # Get an existing object

@hug.object.get(examples=['/fruit'])
    def get_all_of_type(self, model: hug.types.text,...)
        # Get existing objects
```

Instead, I would expect this to behave like a continued extension of the rest of the routing system, just that the class defines a common parent route for the methods. Ideally I'd like the framework to be a flexible and helpful as possible - this feels a bit constrained/opinionated? If I'm wide of the mark or it's intentionally opinionated I would appreciate an explanation - I could then write some docs for it.

Overall I get the impression that it's actually _templated parameterised routes_ that aren't fully developed. For sure they aren't fully documented :)

Very happy to help out. I would need to dive much deeper into the Router code to figure out what needed doing for this though.

**Comment by timothycrosley** [comment]
Thanks for alerting me to this issue! I agree with you that the existing implementation leaves something to be desired. In order to allow full flexibility, which you are correct is indeed a goal, I've implemented support for relative sub routes, as demonstrated here:

https://github.com/timothycrosley/hug/pull/494/files#diff-52d976e719062f2d5d9af708e53ba65eR45

These allow you to add sub routes based off the main route, simply by not prefixing the url with a `/` for the child routes, while still being backward compatible with the old behavior. This is merged into develop and will make its way into the next release.

Thanks!

~Timothy
