### ISSUE TITLE
benchmark test using wrk looks strange

### ISSUE THREAD

**Issue by faviconx** [timothycrosley/hug#465]
I wrote a simply test function just return a dict.

@hug.get('/test')
async def test():
        return {'ret':0}

`hug -f test.py`

`./wrk -t16 -c100 -d30s 'http://127.0.0.1:8000/test'`

threads 16 concurrent connections 100：
Requests/sec:    521.40
threads 16 concurrent connections 1000：
Requests/sec:    537.69
_when I removed the async keyword, the number reached about 600. When I deploy hug using uwsgi , the number looked even worse._

When testing **nginx**:
`./wrk -t16 -c1000 -d30s 'http://127.0.0.1:8080/'`
threads 16 concurrent connections 1000：
Requests/sec:    32356.73

When testing another **tornado** project locally:
`./wrk -t16 -c500 -d30s 'http://127.0.0.1:30080/group/top_by_country'`
threads 16 concurrent connections 1000：
Requests/sec:   1592.83

I tested these on a macbook pro(i5 cpu,memory 8G,SSD), python 3.5.2(pyenv,virtualenv).
Anyone knows wether there was a mistake? What does your test results look like?Am I wrong in some place? Thank you!

**Comment by timothycrosley** [comment]
@davidhyman is correct. Giving the same task, hug is generally has very competitive performance directly underneath that of Falcon: https://raw.githubusercontent.com/timothycrosley/hug/develop/benchmarks/http/RESULTS.md. It's important to remember that hug does automatic jsonification etc by default that many frameworks don't do, even though when developing an API most people do end up needing them. As for `async` in the current hug implementation, async is not for allowing multiple endpoints to be hit at once, but instead only to allow you to more easily do async things within an synchronous API endpoint (like join data from multiple other APIs as an example). Since your not doing any of these type of things in this example it will of course be slower.

Thanks!

~Timothy
