### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by haimari** [timothycrosley/hug#520]
(index):1 XMLHttpRequest cannot load http://example.com:8000/devops_info. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5555' is therefore not allowed access.

I these a way to support cross-domain ?

**Comment by Pusnow** [comment]
Try [hug_middleware_cors](https://github.com/sseemayer/hug_middleware_cors)

**Comment by timothycrosley** [comment]
I've added 2 example approaches for applying Allow Origin, both to all routes via a middle ware and to single routes using a directive:

https://github.com/timothycrosley/hug/commit/ef84f1281765eae84e28cbb621ae6348246e8c52

Note that the middleware was of high quality and has as such since been merged into the hug project.

Thanks!

~Timothy
