### ISSUE TITLE
Capturing and handling hug/falcon exceptions

### ISSUE THREAD

**Issue by MattBSG** [timothycrosley/hug#600]
The current `@hug.exception` decorator is undocumented and I’ve been unable to figure out if it can fit my needs from looking in the code.

I need to catch all errors except in certain cases (I might handle a KeyError myself in an except statement for example) with hug to output predefined uniform json responses. As it currently stands, many of the many libraries I use can error in some edge case etc and will return the stock 500 error response. At the least maybe I could modify the stock response (I haven’t been able to find it in either Hug or Falcon with some quick searches) if someone points me in the right direction or can explain the exception decorator.

When trying to get it working, it captured everything, including exceptions I might raise but were (or would have) been handled. Can anyone point me in the right direction?

**Comment by swilcox** [comment]
My experience has been that anytime an uncaught exception that you've registered with the @hug.exception decorator, it ends up getting handled that way. That's how I think of it, BTW, as a registered handler. So in my use case, I'm using the mongoengine ORM. I have cases where I want to throw the correct HTTP error (409) on a duplicate key on a POST method. MongoEngine is raising a NotUniqueException any time a call attempts to insert a duplicate key. https://github.com/swilcox/badash/blob/e3a2378d0a668714ce1bdea44ec7c6cd65873898/badash-api/app.py#L22 I register this so that it returns the correct error each time. No special coding required in the methods... it just gets handled correctly.

However, if I wanted to do something differently for just one of the methods/routes, you could do a `try` and `except` around the call that might raise that error and then do something differently there. As long as you catch the raised exception, you should be able to override the default behavior that you've defined.
