### ISSUE TITLE
2.4.1+  breaks meinheld worker setup 

### ISSUE THREAD

**Issue by altunyurt** [timothycrosley/hug#737]
This following line breaks the gunicorn + meinheld setup with the error 
```
AttributeError: 'meinheld.input' object has no attribute 'content_length'
```
https://github.com/timothycrosley/hug/blob/06eaffd2058f7683f7e800c7cd1e356d0a5a88c6/hug/interface.py#L607

Using only the gunicorn workers do not cause any problem, it is basically caused due to meinheld.input object does not have any generic attribute setter defined.  

The interesting thing is, if i try to downgrade the package with 
``` pip install hug==2.4.1 ```
it downloads the package from https://files.pythonhosted.org/packages/6f/7d/e5c49f54049a54c27dffb7543bb6b3b2edf2866c160b2532167f5f8e6a33/hug-2.4.1-py2.py3-none-any.whl 

which still has the same line in it. But the 2.4.1 i have on my local setup i've installed a few weeks ago , and the tagged revision on github  do not have that change. So apparently packaging is somehow messed up.

**Comment by timothycrosley** [comment]
Hi @altunyurt,

Thanks for reporting this!

A hot-fix release has just been pushed to pypi to resolve this issue: https://github.com/timothycrosley/hug/releases/tag/2.4.3.

Recently, auto-deploy was set up for this repository. It looks like a wheel was never pushed for 2.4.1, so when auto deploy was complete it added a wheel with that release number and the latest state of the repo. I've removed that wheel from the PYPI index so that issue should be resolved as well now.

Thanks!

~Timothy
